# Learning from https://github.com/stefanprodan/dockprom/blob/master/prometheus/prometheus.yml
version: "3"

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    build: mm_prometheus
    container_name: prometheus
    volumes:
     - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./mm_grafana/provisioning:/etc/grafana/provisioning:rw
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  mm-splunk-app:
    image: splunk/splunk:7.2.9
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=mypassword
      - SPLUNK_APPS_URL=https://github.com/lukemonahan/splunk_modinput_prometheus/releases/download/Release_0.6.0/modinput_prometheus.tar.gz
    restart: unless-stopped
    volumes:
      - ./mm_splunk/mattermost-splunk:/opt/splunk/etc/apps/mattermost-splunk:rw
    ports:
      - "8000:8000"